### ISSUE TITLE
HTTP status code is not handled or not allowed

### ISSUE THREAD

**Issue by ForgottenOneNyx** [polvanrijn/nobelprize-scraper#1]
Hello, I tried scrapping the data of the Nobel data server. Unfortunately I am new the scrapy, after running 

`scrapy crawl url_spider > urls.txt`

Nothing stored in my urls.txt and HTTP status code is not handled or not allowed was the error for each iteration. 

Any ideas? Thanks in advance.

I am running MAC

**Comment by polvanrijn** [comment]
Hey Rachit,

Thanks for the issue. You first need to run `url_spider.py` to make it work. However, this was the first scraper I built. A way more elegant way of doing this (i.e. instead of pre-generating a file with all the urls to scrape) would be to use the built in function by Scrapy:
1. create an array (e.g. `self.array`) containing all urls in `__init__`
1. At the end of your parse function in which you actually scrape all things you can check if your array containing the urls is empty. If this is not the case, pop the last url from the list and call the parse function again with the new url
```
if self.array != []:
    url = self.array.pop()
    request = scrapy.Request(url, callback=self.your_super_parse_function, errback=self.callback_function_if_something_goes_wrong)
    yield request

```

I hope this helped :-)

**Comment by ForgottenOneNyx** [comment]
Hi Pol,

Your solution makes sense, I am going to try that! Thank you so much for your reply! :)
